version: '2'

services:
    db:
        image: postgres
        volumes:
            - ./server/volumes/postgres:/var/lib/postgresql/data
    redis:
        image: redis
        expose:
            - 6379
        volumes:
            - ./server/volumes/redis:/data
    server:
        build: ./server
        command: >
            bash -c "python wait_for_postgres.py &&
                ./manage.py migrate &&
                ./manage.py runserver 0.0.0.0:80"
        volumes:
            - ./server:/code
        depends_on:
            - db
            - redis
        expose:
            - 80
        ports:
            - 8000:80
        environment:
            - REDIS_URL=redis://redis:6379/0
    worker:
        build: ./worker
        volumes:
            - ./worker:/code
        depends_on:
            - redis
        links:
            - server
        environment:
            - REDIS_URL=redis://redis:6379/0
