version: '2'

services:
    server:
        ports:
            - 443:80
        env_file:
            - server/.dockerenv
    ws:
        image: kjagiello/thunderpush
        ports:
            - 8080:8080
